### ISSUE TITLE
SVG styles overridden too aggressively [BUG]

### ISSUE THREAD

**Issue by sportnak** [Faithlife/styled-ui#353] opened 2020-07-14 22:25 UTC
**Describe the bug**
https://github.com/Faithlife/styled-ui/blob/master/components/help-box/styled.jsx#L136 any and all svgs rendered in a helpbox inside a button have all paths changed to blue and there is no way to control that.
**To Reproduce**
1. Render a helpbox
2. Add a button and put an svg inside that button. I rendered a radio inside the helpbox

**Expected behavior**
It should either leave the svg alone or provide an option for 

**Screenshots**
<img width="395" alt="Screen Shot 2020-07-14 at 3 24 47 PM" src="https://user-images.githubusercontent.com/2974028/87482405-2c069400-c5e6-11ea-95c4-bce8ae029d80.png">
<img width="319" alt="Screen Shot 2020-07-14 at 3 25 20 PM" src="https://user-images.githubusercontent.com/2974028/87482446-4476ae80-c5e6-11ea-9069-d6df8fbf1951.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by bryanrsmith** [comment] 2020-07-20 16:27
Looks like it was intended to target some specific icons. Seems solvable with a more specific selector-- either using something like a class name, or by converting the icons or icon containers to styled components and targeting them specifically.

**Comment by sportnak** [comment] 2020-07-21 19:57
@bryanrsmith do you or someone else in the styled-ui realm have the capacity to work on this? It will soon be blocking a key forms feature.

**Comment by bryanrsmith** [comment] 2020-07-21 20:29
Unfortunately there aren't a lot of resources allocated for this project right now. I might have time next week, but no promises. PRs are certainly welcome.

**Comment by sportnak** [comment] 2020-07-28 23:23
@korbinancell do you have any availability to fix this?

**Comment by korbinancell** [comment] 2020-07-28 23:40
If its just a selector issue I can take a crack at it. At the very least Ill investigate some.

**Comment by korbinancell** [comment] 2020-07-31 18:17
@sportnak https://github.com/Faithlife/styled-ui/pull/354

**Comment by korbinancell** [comment] 2020-07-31 20:35
Fixed in #354

**Closed by korbinancell** 2020-07-31 20:36 UTC
Labels: bug
